name: CI

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    # Concurrency is only limited on pull requests. head_ref is only defined on PR triggers so otherwise it will use the random run id and always build all pushes.
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    phpunit-tests:
        strategy:
            fail-fast: false
            matrix:
                php-version: ["7.4", "8.0", "8.1", "8.2"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Installing PHP ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
            - name: Composer Install
              run: composer install -o
            - name: PHPUnit
              run: ./vendor/bin/phpunit -c ./phpunit.xml.dist
